services:
  webapp:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --proxy-headers 
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./data/fastapi:/storage
  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"